### ISSUE TITLE
Another BeerJS plz

### ISSUE THREAD

**Issue by w33ble** [beerjs/phx#1]
Next Wednesday?

@phated you still gonna be on the Paleo kick? That is, do we need to pick a place with wine as well? I've heard great things about [Tops Liquors](https://www.google.com/maps/preview#!q=Tops+Liquors%2C+403+West+University+Drive+%23104%2C+Tempe%2C+AZ&data=!4m10!1m9!4m8!1m3!1d27821!2d-111.9000306!3d33.4193981!3m2!1i1279!2i802!4f13.1)

**Comment by junosuarez** [comment]
I'm calling it now: Beer.js counts as paleo.

**Comment by w33ble** [comment]
Ratified

**Comment by w33ble** [comment]
I'm gonna go ahead and assume this isn't happening today...

**Comment by monteslu** [comment]
we dropped the ball on this.  Maybe next week?

**Comment by w33ble** [comment]
Likely have to be early in the week, 4th is on Thursday.

**Comment by phated** [comment]
Monday is the 1st monday of the month.  That would mean @hafthor is available.

**Comment by phated** [comment]
Been swamped with client work and frozen stuff so didn't get any promotion out or anything.... need to push off again I guess.

**Comment by samrocksc** [comment]
hey dudes: code review declined

**Comment by malakada** [comment]
also i've been waiting around for a bit, yall still coming to tops? 🥺

**Comment by samrocksc** [comment]
there's a hobo dressed like mal in front of tops, it's clothes have rotted off.

**Comment by malakada** [comment]
no that's just luis, he's going through a rough spot. we don't talk about it. 🙊

**Comment by samrocksc** [comment]
![sheldo](https://github.com/beerjs/phx/assets/558796/de16b012-1ac4-4979-beac-30a656ec4e15)
@tooshel
CHANGES REQUESTED

**Comment by malakada** [comment]
<img width="413" alt="image" src="https://github.com/beerjs/phx/assets/992688/810632c7-7985-42e1-855f-0e622e27ff26">

CHANGES REQUESTED TO REQUESTED CHANGE SAM
