### ISSUE TITLE
Someone deleted my branch :((((((((((((((((((((((

### ISSUE THREAD

**Issue by CotyJ** [beerjs/phx#5]
They must have had too many drinks 🤔 🍺

**Comment by charburton18** [comment]
Malak for president

**Comment by tooshel** [comment]
Opps. My bad.

**Comment by malakada** [comment]
speaking of, @tooshel who thought he wasn't added to the repo 😏

**Comment by malakada** [comment]
I believe the dastardly culprit who committed (ahem) such a heinous act appropriately addressed their failings as I do see your contribution live currently here: https://github.com/beerjs/phx/blob/d7a00dc7c450f2e69c059205482693cd6186e8b3/src/components/Navigation.astro#L7-L14

With that, I'm going to close this issue as resolved. 😌
